### ISSUE TITLE
Y-axis values truncated using `view_run_metrics`

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tfruns#1]
On y-axis, 400 appears to be 4 (top plot) and 30 appears to be 3 (bottom plot). Am I using `view_run_metrics` incorrectly? See the code and screenshot below:

```
> dput(history)
structure(list(mean_losses = c(369.706113815308, 454.547627449036
), total_losses = c(2957.64891052246, 3636.38101959229)), .Names = c("mean_losses", 
"total_losses"), row.names = c(NA, -2L), class = "data.frame")
> tfruns::view_run_metrics(history)
```

![image](https://user-images.githubusercontent.com/4269898/29244708-f5cca11a-7f8c-11e7-8e6e-d17b7cdbd4e0.png)

**Comment by jjallaire** [comment]
You are using it correctly unfortunately it looks like the library we are using for plotting is getting the axis wrong. There may be something we can do with specification of a custom axis format. Let me see what I can do.
