### ISSUE TITLE
should metrics viewer should redraw ticks when redrawn?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfruns#12]
When training a model for an unknown number of steps (ie, when I just want to exhaust all available data during a training run), the metrics viewer never draws any new x axis ticks, leaving a view like the following:

![screen shot 2017-09-26 at 4 02 14 pm](https://user-images.githubusercontent.com/1976582/30888216-19c3dd94-a2d4-11e7-8fe9-b4f389ba996d.png)

Is it possible to have the x-axis redrawn for this case?

**Comment by jjallaire** [comment]
We actually already adjust the y-axis on updates (to give it a fixed max of
1 if the metric is accuracy). We do that here:

https://github.com/rstudio/tfruns/blob/master/inst/views/components/metrics_charts.html#L223

This is the function it calls:

https://github.com/rstudio/tfruns/blob/master/inst/views/components/metrics_charts.html#L159-L166

There we determine the current steps/epochs by inspecting the data. We
could easily compare that to the current x-axis max and adjust as
necessary. Do you want to take a shot at this?

**Comment by kevinushey** [comment]
I'll give it a shot!

**Comment by jjallaire** [comment]
Okay, great. Let me know if anything isn't clear.

**Comment by jjallaire** [comment]
I was refactoring that code for inclusion in the comparison view and so went ahead and made the change: https://github.com/rstudio/tfruns/commit/680685c45ea80a2ed59eb005d23185a6a6689771

Let me know if this behaves as you expect.

**Comment by kevinushey** [comment]
Unfortunately it doesn't. I suspect that because the c3 chart is initialized with a set of tick values, those are used regardless of whether the span of values increases over time. Setting it to `null` doesn't look perfect either (a tick gets drawn for _every_ time point, which ends up looking noisy).

I'll see if I can find a middle ground and send a PR.

**Comment by kevinushey** [comment]
Fixed up with https://github.com/rstudio/tfruns/commit/680685c45ea80a2ed59eb005d23185a6a6689771
