### ISSUE TITLE
y axis labels occasionally truncated oddly

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfruns#13]
E.g.

<img width="273" alt="screen shot 2017-09-27 at 10 10 29 am" src="https://user-images.githubusercontent.com/1976582/30927102-2cd46a50-a36c-11e7-96a5-06e8e4b6f0e8.png">

Note that 100 has been rendered as 1 instead.

**Comment by jjallaire** [comment]
I think that the problem is my regex here: https://github.com/rstudio/tfruns/blob/master/inst/views/components/metrics_charts.html#L191-L200

I'll put together a PR that fixes this

**Comment by jjallaire** [comment]
PR is here: https://github.com/rstudio/tfruns/pull/16

A quick review as a sanity check would be appreciated. By way of background, this is intended to address situations where JavaScript floating point yields labels like 1.00000005 (this is a known issue with d3 axis formatting)
