### ISSUE TITLE
Getting cannot fork error during untar when trying to view run on Windows7

### ISSUE THREAD

**Issue by ledgerW** [rstudio/tfruns#23]
Hi,

All of the runs folders populate as expected during training and tuning runs.  But unable to launch results dashboard.  Any guidance?  Thanks!

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.3                         
year           2017                        
month          11                          
day            30                          
svn rev        73796                       
language       R                           
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree 

-----
view_run("runs/2018-03-03T06-44-28Z")

C:\PROGRA\~2\Gow\bin\tar.exe: Cannot fork: Function not implemented
C:\PROGRA\~2\Gow\bin\tar.exe: Error is not recoverable: exiting now

Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: running command 'tar.exe -zxf "runs/2018-03-03T06-44-28Z/tfruns.d/source.tar.gz" -C "C:/Users/USERNAME/AppData/Local/Temp/Rtmpqeq0We/file33a86bbe2bda"' had status 2 
2: In utils::untar(source_tarball, exdir = source_tmp_dir, compressed = TRUE) :
  ‘tar.exe -zxf "runs/2018-03-03T06-44-28Z/tfruns.d/source.tar.gz" -C "C:/Users/USERNAME/AppData/Local/Temp/Rtmpqeq0We/file33a86bbe2bda"’ returned error code 2
3: In file(con, "r") :
  cannot open file 'C:\Users\USERNAME\AppData\Local\Temp\Rtmpqeq0We\file33a86bbe2bda/source/my_rnn.R': No such file or directory

**Comment by jjallaire** [comment]
It looks like it's finding a copy of tar.exe on your path. I just made a change to use the internal tar library so hopefully this will resolve the problem for you (let me know)

**Comment by ledgerW** [comment]
Yep, that fixed it.  Thanks.  I'll close this issue.

**Comment by kaiher** [comment]
I have the same trouble to install a package from Github. Could you let me know how to make a change to use the internal tar library?
