### ISSUE TITLE
Worse performance with more files in working directory

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/tfruns#31]
`training_run()` scans the whole working directory for changes in `with_changed_file_copy()` which has (in my case) significant performance implications. 

https://github.com/rstudio/tfruns/blob/master/R/training_run.R#L228

In what sense is that necessary? It seems sensible to me to limit this to the directory of the training script, which I implemented in my [fork](https://github.com/lorenzwalthert/tfruns/tree/performance). However, I am not sure about dependencies of this part of the code. What's your opinion? Alternatively, we could introduce an argument (which defaults to a global option) to handle which files are scanned.

**Comment by lorenzwalthert** [comment]
Thanks for your quick response 👍  
> [...] Issue here might be that your working directory is above the training script directory[...]

Indeed, I have an RStudio Project for the analysis part of my thesis. The root directory of the project is my working directory. `tfruns` is a sub-directory. Within `tfruns`, I create a new folder for each class of experiments I am running. 
```
- thesis-root
  - ...
  - tfruns
    - experiment-1
```

So maybe my directory structure is different from what you had in mind when defining this logic. What am I missing? Maybe I need a better understanding of the capturing of side-effects and how it plays together with version control, as there is some potential for redundancy.

I just feel the having to set the working directory to something different than the project root is not very common and imposes some restrictions.

I think I tried `with::with_dir()` but I think there were some problems associated with this approach in conjunction with viewing runs afterwards in tensorboard because the working directory at the time I call tensorboard is not the same as at the time I call `training_run(()`. May revert with a concrete example.

**Comment by lorenzwalthert** [comment]
Yes sorry I forgot that. This excerpt from my directory tree should suffice for understanding my situation:
```
- thesis-root
  - ...
  - tfruns
    - experiment-1
    - experiment-2
- code 
  - execute
    - estimators
      - meta-runner (contains a call to `tuning_run()`)
      - runner (is the file executed from `tuning_run()`)
      - ...
    - ..
  - ..

```

So in my `meta-runner.R`, I have this code: 
```r
run_scope <- here::here("tfruns/experiment-1") # here::here() converts relative path to absoute path
tuning_run(
  here::here("code/execute/estimators/runner.R"), 
  runs_dir = run_scope, 
  flags = list(...)
)
```
After finishing an experiment, I commit the files in `code/execute/estimators/` and update both the `flags` argument and the `run_scope` in `meta-runner.R` for the next experiment, sometimes I also change code in `runner.R`. The reason why I use the same runner and meta-runner is that that way I can avoid duplication, as most parts of the code in these two files remains the same across experiments. In addition, I can easily use `git diff` to see what changes between the experiments and use git to go back and forth between experiments and no adjustment of file paths is needed. I do not commit any files in `tfruns`. I hope this makes my use case more clear.

**Comment by jjallaire** [comment]
Okay, given how customized your directory structure is I don't think any amount of auto-detection would work here. I've added an `artifacts_dir` argument to `training_run()` and `tuning_run()` which will let you control this. In your case if there are no artifacts you are attempting to capture (e.g. saved models) then you can just pass `NULL` to suppress the behavior. Here is the commit: https://github.com/rstudio/tfruns/commit/b134f2dd66c49a8d1307ed1ba7f32807977accaa

**Comment by lorenzwalthert** [comment]
Thanks. I will have a look and report back in case of any problems.
