### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by gsteinbu** [rstudio/tfruns#46]
I like the principle of tfruns, however, it seems to me not maintained anymore (last commit almost a year from now). Hence, my question(s):  Is tfruns still maintained, or is there an alternative I should use (e.g., just use tensorboard)?

**Comment by dfalbel** [comment]
@gsteinbu yes, this package is still maintained. I will be happy to make patches if you find issues using it.

**Comment by gsteinbu** [comment]
Great, thanks @dfalbel! Just posted an issue #47.
