### ISSUE TITLE
Control dimensions of plots saved during training

### ISSUE THREAD

**Issue by jemus42** [rstudio/tfruns#51]
When the training script contains a small plot, it's neatly displayed in the window opened by `view_run()`, but in my particular case the plot I'd like to look at is a little busy with multiple facets, therefore needing a bigger size so I can actually make something out.

My current workaround is to manually save the plot (I've tried both `ggsave` and manual `png(...) <...> dev.off()`), which does the trick regarding adjustable dimensions, but it comes at a cost:

I have not yet quite figured out the paths used during plotting – it looks like plots are saved in my project root by default and then copied (*not* moved because they remain there) to the run's directory (but then again, _not_ in the `plots` directory.

Before I dive deeper into paths and environments, I'd rather ask: Is there a better way to plot at larger dimensions without having to explicitly save the plots?

**Comment by dfalbel** [comment]
Currently there's no builtin way to save higher dimension plots. However you can save to the `plots` directory by using a path like this. Plots saved to this directory can be seen in the `outputs` tab  when you use `tfruns::view_run`.

```
file.path(tfruns::run_dir(), "plots", "myplot.png")
```
