### ISSUE TITLE
enforcing types on flags?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/tfruns#6]
If you have a `flags.yml` containing e.g.

```
default:
    numeric: "whoops",
    boolean: "bad-parameter"
```

And a flags declaration:

```
FLAGS <- flags(
    flag_numeric("numeric", 0),
    flag_boolean("boolean", FALSE)
)
```

The `flags()` invocation succeeds, but with a warning:

```
> flags(
+     flag_numeric("numeric", 0),
+     flag_boolean("boolean", FALSE)
+ )
Warning in parse_flags(FLAGS, config, file, arguments) :
  NAs introduced by coercion
    name    type value description
 numeric numeric    NA          NA
 boolean boolean    NA          NA
```

I wonder if this should instead be an error?

**Comment by jjallaire** [comment]
Yes, it should definitely be an error! Made that change here: https://github.com/rstudio/tfruns/commit/c9bf887bdfe52c8da4d48cf011c6b9d281c24bc8
